// Capture only in dedicated marketing simulators. Never connected physical devices.
import {spawnSync} from 'node:child_process';
import {readFileSync,writeFileSync,mkdirSync,existsSync,statSync,rmSync,copyFileSync} from 'node:fs';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {setTimeout as sleep} from 'node:timers/promises';
import {randomUUID} from 'node:crypto';
import {COPY} from './creative-copy.mjs';
const dir=fileURLToPath(new URL('.',import.meta.url)),root=join(dir,'../../..'),raw=join(dir,'raw');
const APP=process.env.IOS_SHOTS_APP||'/private/tmp/owc-store-locales-build/Build/Products/Debug-iphonesimulator/App.app';
const WATCH=process.env.IOS_SHOTS_WATCH_APP||'/private/tmp/owc-store-locales-build/Build/Products/Debug-watchsimulator/DoneAt Watch App.app';
const bundle='com.rainif.offworkcountdown.macappstore';
const devices={iphone:'3C9FDCBC-0FA4-4E18-BFF4-2A8C36877966',ipad:'6F5E631B-982F-4911-928B-A28B8C63BD81',watch:'BCE439EB-0B3F-4317-BFA4-A40DC5CEFBFD'};
const catalog=JSON.parse(readFileSync(join(root,'src-mobile/ios/App/App/Localizable.xcstrings'),'utf8')).strings;
const holidays=JSON.parse(readFileSync(join(dir,'holiday-demos.json'),'utf8')).scenes;
const langs=(process.env.IOS_SHOTS_LANGUAGE||Object.keys(COPY).join(',')).split(',');
const platforms=(process.env.IOS_SHOTS_PLATFORM||'iphone,ipad,watch').split(',');
const scenes=(process.env.IOS_SHOTS_SCENES||'1,2,3,4,calendar,focus').split(',');
const text=(lang,key)=>{const v=catalog[key]?.localizations?.[lang]?.stringUnit?.value;if(!v)throw new Error(`Missing ${lang} ${key}`);return v;};
function run(command,args,allow=false){const r=spawnSync(command,args,{encoding:'utf8',timeout:180000,env:{...process.env,SIMCTL_CHILD_TZ:process.env.IOS_SHOTS_TIME_ZONE||'Asia/Shanghai'}});if(r.status&&!allow)throw new Error(`${command} ${args.join(' ')}\n${r.stderr}`);return(r.stdout||'').trim();}
const sim=(args,allow)=>run('xcrun',['simctl',...args],allow);
function stop(id,b=bundle){sim(['terminate',id,b],true);}
function container(id){return sim(['get_app_container',id,bundle,'data']);}
function archivePath(id){return join(container(id),'Library/Application Support/owc-records/archive.json');}
function decode(id){const e=JSON.parse(readFileSync(archivePath(id),'utf8'));return[e,JSON.parse(Buffer.from(e.document,'base64'))];}
function encode(id,e,a){e.document=Buffer.from(JSON.stringify(a)).toString('base64');writeFileSync(archivePath(id),JSON.stringify(e));}
function daytime(){const now=new Date(),offset=15-now.getUTCHours();return{offset,zone:offset===0?'Etc/UTC':`Etc/GMT${offset>0?'-':'+'}${Math.abs(offset)}`};}
function baseArgs(lang){const locale=COPY[lang].asc.replace('-','_');return['-ios.native.qaTimeZone',process.env.IOS_SHOTS_TIME_ZONE||'Asia/Shanghai','-AppleLanguages',`(${lang==='zh-CN'?'zh-Hans':lang==='zh-TW'?'zh-Hant':lang})`,'-AppleLocale',locale,'-ios.native.recordsTimeZone',process.env.IOS_SHOTS_TIME_ZONE||'Asia/Shanghai','-ios.native.languageOverride',lang,'-ios.native.countdownStarted','YES','-ios.native.onboardingComplete','YES','-ios.native.releaseNotesSeen','3.2.0','-ios.native.debugAlwaysOnboarding','NO','-ios.native.debugPlusAuthorized','YES','-ios.native.plusHasSeenIntro','YES','-theme','light','-ios.native.liveActivityEnabled','NO','-ios.native.selectedTab','timer','-ios.native.qaOrientation','portrait','-ios.native.qaDebugScenario','','-ios.native.qaFocusScenario','','-ios.native.qaRecordsScale','','-ios.native.qaRoute','','-ios.native.qaOnboardingPage','','-UIPreferredContentSizeCategoryName','UICTContentSizeCategoryL'];}
function launch(id,lang,extra=[]){stop(id);rmSync(join(container(id),'Library/Caches/qa-surface.txt'),{force:true});sim(['launch','--terminate-running-process',id,bundle,...baseArgs(lang),...extra]);}
async function capture(id,path,marker,delay=2500){await sleep(delay);const m=join(container(id),'Library/Caches/qa-surface.txt');const actual=existsSync(m)?readFileSync(m,'utf8').trim():'';if(!actual.includes(marker)&&!(marker==='schedule'&&actual==='settings')&&!(marker==='route.focus'&&['settings','focus'].includes(actual)))throw new Error(`Wrong surface ${actual}, expected ${marker}`);for(let attempt=0;attempt<5;attempt++){sim(['io',id,'screenshot','--type=png','--mask=ignored',path]);const visible=run('python3',['-c','from PIL import Image,ImageStat;import sys;im=Image.open(sys.argv[1]).convert("L");w,h=im.size;print(max(0,ImageStat.Stat(im.crop((int(w*.1),int(h*.2),int(w*.9),int(h*.55)))).var[0])**0.5 if ImageStat.Stat(im.crop((0,int(h*.15),int(w*.02),int(h*.5)))).mean[0]>220 else 0)',path]);if(statSync(path).size>80000&&Number(visible)>12)break;if(attempt===4)throw new Error(`Blank capture ${path}`);await sleep(3000);}if(/-[13]\.png$/.test(path)){const choices=[path];for(let n=1;n<=5;n++){await sleep(137);const candidate=path.replace('.png',`-candidate-${n}.png`);sim(['io',id,'screenshot','--type=png','--mask=ignored',candidate]);choices.push(candidate);}const scored=choices.map(p=>[Number(run('python3',['-c','from PIL import Image,ImageStat,ImageFilter;import sys;im=Image.open(sys.argv[1]).convert("L");w,h=im.size;print(ImageStat.Stat(im.crop((int(w*(.55 if w>1500 else .6)),int(h*(.09 if w>1500 else .13)),int(w*(.69 if w>1500 else .82)),int(h*(.17 if w>1500 else .22)))).filter(ImageFilter.FIND_EDGES)).mean[0])',p])),p]).sort((a,b)=>b[0]-a[0]);if(scored[0][1]!==path)copyFileSync(scored[0][1],path);choices.slice(1).forEach(p=>rmSync(p));}console.log(path);}
const workNames={'zh-CN':['白班','休息'],'zh-TW':['日班','休息'],en:['Day','Rest'],de:['Tag','Frei'],fr:['Jour','Repos'],es:['Día','Libre'],it:['Giorno','Riposo'],pt:['Dia','Folga'],ja:['日勤','休み'],ko:['주간','휴무'],ru:['День','Отдых'],tr:['Gündüz','İzin'],id:['Siang','Libur'],vi:['Ca ngày','Nghỉ'],th:['กะกลางวัน','หยุด'],'hi-IN':['दिन','आराम'],ar:['نهاري','راحة']};
function regularSeed(id,lang){if(!existsSync(archivePath(id)))return;const[e,a]=decode(id);a.focusSessions=[];a.focusTasks=[];delete a.focusPlanningConfiguration;a.timeZoneIdentifier='Asia/Shanghai';Object.assign(a.syncedPreferences,{recordsTimeZoneIdentifier:'Asia/Shanghai',languageOverride:lang,startMinutes:540,endMinutes:1020,workdays:lang==='ar'?[0,1,2,3,4]:[1,2,3,4,5],lunchEnabled:true,lunchStartMinutes:720,lunchDurationMinutes:60});delete a.extendedSchedule;a.careerPeriods.forEach(p=>p.timeZoneIdentifier='Asia/Shanghai');const hours={startTime:'09:00',endTime:'17:00',workdays:lang==='ar'?[0,1,2,3,4]:[1,2,3,4,5],schedule:{mode:'classic'},breakStartTime:'12:00',breakDurationMinutes:60};a.scheduleSnapshots.forEach(s=>{s.configurationData=Buffer.from(JSON.stringify(hours)).toString('base64');});encode(id,e,a);}
function calendarSeed(id,lang){const[e,a]=decode(id),scene=holidays.find(s=>s.ascLocale===COPY[lang].asc),now=Date.now();
 a.careerPeriods.forEach(p=>p.startsOn='2025-01-01');a.recordsStartedOn='2025-01-01';a.scheduleSnapshots.forEach(s=>s.effectiveFrom='2025-01-01');a.dayOverrides=[];a.rosterDays=[];a.calendarExceptions=[];
 const work=randomUUID().toUpperCase(),rest=randomUUID().toUpperCase();
 const make=(kind,index,id)=>({id,name:workNames[lang][index],kind,startMinutes:540,endMinutes:1020,breakEnabled:kind==='work',breakStartMinutes:720,breakDurationMinutes:60,colorHex:kind==='work'?'#F45A1E':'#69B792',isArchived:false});
 a.extendedSchedule={isEnabled:true,shiftTypes:[make('work',0,work),make('rest',1,rest)],rule:{preset:'weekly',anchorDayKey:'2026-01-05',days:scene.regionIdentifier==='SA'?[work,work,work,work,rest,rest,work]:[work,work,work,work,work,rest,rest]},holidayRegionIdentifier:scene.regionIdentifier,timeZoneIdentifier:'Asia/Shanghai',editedAtMs:now,editCount:1,editTieBreaker:randomUUID().toUpperCase()};
 const hours={startTime:'09:00',endTime:'17:00',workdays:scene.regionIdentifier==='SA'?[0,1,2,3,4]:[1,2,3,4,5],schedule:{mode:'classic'},breakStartTime:'12:00',breakDurationMinutes:60,extendedContent:{shiftTypes:a.extendedSchedule.shiftTypes,rule:a.extendedSchedule.rule,holidayRegionIdentifier:scene.regionIdentifier}};a.scheduleSnapshots.forEach(s=>{s.effectiveFrom='2025-01-01';s.configurationData=Buffer.from(JSON.stringify(hours)).toString('base64');});a.syncedPreferences.scheduleMode='classic';a.syncedPreferences.recordsTimeZoneIdentifier='Asia/Shanghai';a.syncedPreferences.languageOverride=lang;a.syncedPreferences.workdays=scene.regionIdentifier==='SA'?[0,1,2,3,4]:[1,2,3,4,5];encode(id,e,a);return scene.selectedDate;}
function focusSeed(id,lang){const[e,a]=decode(id),{offset,zone}=daytime(),now=Date.now(),d=new Date(now+offset*3600000),day=d.toISOString().slice(0,10);const at=(h,m=0)=>Date.parse(`${day}T${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:00Z`)-offset*3600000;
 delete a.extendedSchedule;a.timeZoneIdentifier=zone;Object.assign(a.syncedPreferences,{recordsTimeZoneIdentifier:zone,startMinutes:540,endMinutes:1080,workdays:[0,1,2,3,4,5,6],lunchEnabled:true,lunchStartMinutes:720,lunchDurationMinutes:60,languageOverride:lang});
 a.careerPeriods.forEach(p=>{p.startsOn='2025-01-01';p.timeZoneIdentifier=zone});a.scheduleSnapshots.forEach(s=>{const hours=JSON.parse(Buffer.from(s.configurationData,'base64'));hours.startTime='09:00';hours.endTime='18:00';hours.workdays=[0,1,2,3,4,5,6];delete hours.extendedContent;s.configurationData=Buffer.from(JSON.stringify(hours)).toString('base64');});
 a.focusTasks=COPY[lang].demoTasks.map((title,i)=>({id:i===0?'00000000-0026-4000-A000-000000000320':randomUUID().toUpperCase(),title,icon:'focus',createdAtMs:now,editedAtMs:now,editCount:1,editTieBreaker:randomUUID().toUpperCase(),estimatedPomodoros:1,isFavorite:false,plannedForDate:day,scheduledStartAtMs:at(14+i),sortIndex:i}));
 a.focusSessions=[{id:randomUUID().toUpperCase(),taskID:a.focusTasks[0].id,kind:'focus',timeZoneIdentifier:zone,shiftAnchorDate:day,startedAtMs:now-3*60000,plannedEndAtMs:now+22*60000,plannedEndReason:'completed',editedAtMs:now,editCount:1,editTieBreaker:randomUUID().toUpperCase()}];
 const assignments=[[9,0],[9,30],[10,0],[10,30],[11,10],[11,40],[13,0],[13,30],[14,0],[14,40],[15,10],[15,40],[16,10],[16,50],[17,20]].map(([h,m],i)=>({blockStartAtMs:at(h,m),kind:'task',taskID:a.focusTasks[i<8?1:i<12?0:2].id,taskTitle:a.focusTasks[i<8?1:i<12?0:2].title,taskIcon:'focus'}));
 a.focusPlanningConfiguration={plans:[{dayKey:day,shiftStartAtMs:at(9),assignments}],templates:[],autoAppliedDayKeys:[day],focusMinutes:25,shortBreakMinutes:5,longBreakMinutes:15,longBreakEvery:4,editedAtMs:now,editCount:1,editTieBreaker:randomUUID().toUpperCase()};encode(id,e,a);return`${String(d.getUTCHours()).padStart(2,'0')}:${String(d.getUTCMinutes()).padStart(2,'0')}`;}
mkdirSync(raw,{recursive:true});
for(const platform of platforms){const id=devices[platform];if(!id)throw new Error(platform);sim(['boot',id],true);sim(['bootstatus',id,'-b']);if(process.env.IOS_SHOTS_SKIP_INSTALL!=='1')sim(['install',id,platform==='watch'?WATCH:APP]);sim(['ui',id,'appearance','light'],true);sim(['status_bar',id,'override','--time','14:22','--batteryState','charged','--batteryLevel','100','--wifiMode','active','--wifiBars','3'],platform==='watch');
 if(platform!=='watch'){const p=archivePath(id);if(existsSync(p)){const backup=join(raw,`${platform}-before-capture-archive.json`);if(!existsSync(backup))copyFileSync(p,backup);const[e,a]=decode(id);if(e.sync)e.sync.syncEnabled=false;encode(id,e,a);}}
 if(platform==='watch'){for(const lang of langs){const b=bundle+'.watchkitapp';stop(id,b);const labels=[['Working','widgetWorking'],['Break','extendedBreak'],['Resting','recordsRestDay'],['Overtime','overtime'],['Finished','offWorkToday']].flatMap(([n,key])=>[`-owcWatchReview${n}Label`,text(lang,key)]);sim(['launch',id,b,'-AppleLanguages',`(${lang})`,'-owcWatchReviewState','working','-owcWatchReviewLocale',lang,'-owcWatchReviewTimeZone','Asia/Shanghai',...labels]);await sleep(5000);const watchPath=join(raw,`${COPY[lang].stem}-watch-3.2.0.png`);for(let attempt=0;attempt<6;attempt++){sim(['io',id,'screenshot',watchPath]);const count=Number(run('python3',['-c','from PIL import Image;import sys;im=Image.open(sys.argv[1]).convert("L");w,h=im.size;print(sum(p>150 for p in im.crop((int(w*.1),int(h*.43),int(w*.9),int(h*.62))).getdata()))',watchPath]));if(count>1000)break;if(attempt===5)throw new Error(`Watch digits missing ${lang}`);await sleep(2500);}console.log(watchPath);}stop(id,bundle+'.watchkitapp');}
 else{for(const lang of langs){const prefix=COPY[lang].stem+(platform==='ipad'?'-ipad':'');if(platform==='ipad'){stop(id);const systemLanguage=lang==='zh-CN'?'zh-Hans':lang==='zh-TW'?'zh-Hant':lang==='hi-IN'?'hi':lang;sim(['spawn',id,'defaults','write','NSGlobalDomain','AppleLanguages','-array',systemLanguage]);sim(['spawn',id,'defaults','write','NSGlobalDomain','AppleLocale',COPY[lang].asc.replace('-','_')]);sim(['spawn',id,'launchctl','stop','com.apple.SpringBoard']);await sleep(10000);}for(const scene of scenes){delete process.env.IOS_SHOTS_TIME_ZONE;sim(['status_bar',id,'override','--time','14:22']);const map={'1':['-ios.native.qaDebugScenario','working'],'2':['-ios.native.debugAlwaysOnboarding','YES','-ios.native.qaOnboardingPage','5'],'3':['-ios.native.qaDebugScenario','lunch'],'4':['-ios.native.qaRecordsScale','year']};if(map[scene]){stop(id);regularSeed(id,lang);launch(id,lang,map[scene]);await capture(id,join(raw,`${prefix}-${scene}.png`),scene==='2'?'onboarding':scene==='4'?'records':'timer',scene==='4'?15000:10000);}
 else{launch(id,lang,['-ios.native.qaRecordsScale','year']);await sleep(5000);stop(id);if(scene==='calendar'){const date=calendarSeed(id,lang);launch(id,lang,['-ios.native.selectedTab','settings','-ios.native.qaRoute','schedule','-ios.native.qaScheduleDate',date]);await capture(id,join(raw,`${prefix}-calendar.png`),'schedule',10000);}else{const time=focusSeed(id,lang);process.env.IOS_SHOTS_TIME_ZONE=daytime().zone;sim(['status_bar',id,'override','--time',time]);launch(id,lang,['-ios.native.selectedTab','focus','-ios.native.qaRoute','focus']);await capture(id,join(raw,`${prefix}-focus.png`),'route.focus',10000);}}}}stop(id);}
 sim(['shutdown',id]);}
