// Run after composing HTML. Measures actual font/line bounds in Chrome.
import{readdirSync,readFileSync,writeFileSync,mkdtempSync,rmSync}from'node:fs';
import{join}from'node:path';import{tmpdir}from'node:os';import{fileURLToPath}from'node:url';import{spawn}from'node:child_process';
const out=process.env.IOS_CREATIVE_OUT||fileURLToPath(new URL('./out/creative-3.2.0',import.meta.url));
const files=readdirSync(out).filter(f=>/^.+-(iphone|ipad)-0[1-8]-.+\.html$/.test(f));
const sources=files.map(file=>({file,html:readFileSync(join(out,file),'utf8').replace(/<img[^>]*>/g,'')}));
if(sources.some(source=>!source.html.includes('layoutReady')))throw new Error('All pages must be rendered with the current layout before auditing');
if(files.length!==272)throw new Error(`Expected 272 HTML pages, got ${files.length}`);
const payload=JSON.stringify(sources).replaceAll('<','\\u003c');
const html=`<!doctype html><meta charset="utf-8"><body><pre id="result">WAIT</pre><script>const sources=${payload};const findings=[];(async()=>{for(const source of sources){const frame=document.createElement('iframe');frame.style='position:fixed;width:1032px;height:1434px;left:-4000px';document.body.append(frame);await new Promise(r=>{frame.onload=r;frame.srcdoc=source.html});await frame.contentDocument.fonts.ready;while(frame.contentDocument.body.dataset.layoutReady!=='true')await new Promise(resolve=>setTimeout(resolve,10));const doc=frame.contentDocument;for(const e of doc.querySelectorAll('.line,.label,.subline,.foot,.watch-note small')){const range=doc.createRange();range.selectNodeContents(e);const bounds=range.getBoundingClientRect(),box=e.getBoundingClientRect();if(bounds.width>box.width+2)findings.push({file:source.file,text:e.textContent,actual:bounds.width,available:box.width});}const title=doc.querySelector('h1'),sub=doc.querySelector('.sub');if(title?.textContent&&sub?.textContent&&title.getBoundingClientRect().bottom>sub.getBoundingClientRect().top-24)findings.push({file:source.file,issue:'Title/subtitle vertical spacing',titleBottom:title.getBoundingClientRect().bottom,subtitleTop:sub.getBoundingClientRect().top});const body=doc.body.getBoundingClientRect(),art=doc.querySelector('.phone,.watch'),editorial=doc.querySelector('.editorial');if(!doc.body.classList.contains('hero')&&!doc.body.classList.contains('hero-continuation')&&art&&editorial&&art.getBoundingClientRect().top<editorial.getBoundingClientRect().bottom+24)findings.push({file:source.file,issue:'Device/header collision'});const widgets=doc.querySelector('.widgets-art'),foot=doc.querySelector('.foot');if(widgets&&foot){for(const crop of widgets.children){const box=crop.getBoundingClientRect();if(box.bottom>foot.getBoundingClientRect().top-24||box.left<body.left+20||box.right>body.right-20||box.top<editorial.getBoundingClientRect().bottom+24)findings.push({file:source.file,issue:'Widget/footer or page boundary collision'});}}frame.remove();}document.getElementById('result').textContent=JSON.stringify({pages:sources.length,findings});})();</script>`;
const path=join(out,'layout-audit.html');writeFileSync(path,html);
const profile=mkdtempSync(join(tmpdir(),'owc-layout-'));
const chrome=spawn(process.env.CHROME_BIN||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--disable-gpu','--disable-background-networking','--allow-file-access-from-files',`--user-data-dir=${profile}`,'--dump-dom','--virtual-time-budget=45000',`file://${path}`],{stdio:['ignore','pipe','ignore']});
let result='';chrome.stdout.on('data',b=>result+=b);const timer=setTimeout(()=>chrome.kill('SIGKILL'),90000);await new Promise(r=>chrome.on('exit',r));clearTimeout(timer);rmSync(profile,{recursive:true,force:true,maxRetries:5,retryDelay:100});
const raw=result.match(/<pre id="result">(.*?)<\/pre>/s)?.[1];if(!raw||raw==='WAIT')throw new Error('Layout audit did not complete');const report=JSON.parse(raw.replaceAll('&amp;','&').replaceAll('&lt;','<').replaceAll('&gt;','>'));writeFileSync(join(out,'layout-audit.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));if(report.findings.length)process.exitCode=1;
