// Store copy is editorial, not a literal translation. Explicit lines are intentional.
// hero: 3–4 short lines in the clear left strip of the two-panel opening.
// Each entry: label, headline lines (last line orange), supporting lines.
const page = (label, title, sub = '') => ({label, lines:title.split('|'), sub:sub.split('|')});
const set = (asc, stem, hero, heroSize, intro, free, rows, demoTasks) => ({asc,stem,hero:hero.split('|'),heroSize,intro,free,pages:rows.map(r=>page(...r)),demoTasks});
export const COPY = {
 'zh-CN':set('zh-Hans','zh','下班，|值得|期待。',100,'你的时间，|不止属于工作。','免费使用',[
 ['每一秒，都离下班更近。',''],['现在，也在 Apple Watch 上','抬腕，|离下班更近。','下班倒计时，免费随身。'],['月历排班 · 节假日与调休','哪天上班，|一眼明白。','月历排班，随改随见。|开启地区模板，节假日与调休一起安排。'],['记录 · DoneAt Plus 年视图','忙过的日子，|都有迹可循。','用颜色回看一年的工时，|看见自己的工作节奏。'],['番茄钟 · DoneAt Plus','专心一会儿，|再歇一会儿。','把待办放进专注时段，|工作与休息，都有自己的节奏。'],['随时可见','不打开，|也看得到。','灵动岛 · 锁定屏幕 · 小组件'],['给休息留一点空间','中途休息，|不算工时。','自动扣除休息时段，按实际工时倒数。']],['整理项目资料','完成设计方案','回复工作邮件']),
 'zh-TW':set('zh-Hant','zh-tw','下班，|值得|期待。',100,'你的時間，|不只屬於工作。','免費使用',[
 ['每一秒，都離下班更近。',''],['現在，也在 Apple Watch 上','抬起手腕，|下班更近了。','下班倒數，免費隨身。'],['月曆排班 · 國定假日','哪天上班，|一眼明白。','排班一改，月曆就更新。|開啟地區範本，一起安排假日。'],['紀錄 · DoneAt Plus 年檢視','忙過的日子，|都有跡可循。','用顏色回顧一年的工時，|看見自己的工作節奏。'],['番茄鐘 · DoneAt Plus','專心一會兒，|再歇一會兒。','把待辦放進專注時段，|工作與休息，都有自己的節奏。'],['隨時可見','不打開，|也看得到。','動態島 · 鎖定畫面 · 小工具'],['給休息留一點空間','中途休息，|不算工時。','自動扣除休息時段，依實際工時倒數。']],['整理專案資料','完成設計方案','回覆工作郵件']),
 en:set('en-US','en','After work,|time for|you.',76,'Your time is more|than work.','Free to use',[
 ['Every second, closer to clocking out.',''],['Now on Apple Watch','A glance.|Closer to done.','Your shift countdown, free on your wrist.'],['Schedules · Public holidays','Your month.|At a glance.','Edit a shift. See it on your calendar.|Turn on a region’s holiday template.'],['Records · Year view with DoneAt Plus','Your work,|in perspective.','A year of working hours, in color.|Find your own rhythm.'],['Pomodoro · DoneAt Plus','Time to focus.|Time to pause.','Give your tasks a place in your day.|Make room for breaks, too.'],['Always in sight','No need|to open it.','Dynamic Island · Lock Screen · Widgets'],['Make room for a break','Break time.|Your time.','Breaks are excluded from working time.']],['Review project notes','Draft the proposal','Reply to emails']),
 de:set('de-DE','de','Feierabend.|Zeit für|dich.',72,'Deine Zeit gehört|nicht nur der Arbeit.','Kostenlos nutzbar',[
 ['Jede Sekunde näher am Feierabend.',''],['Jetzt auf der Apple Watch','Ein Blick.|Bald Feierabend.','Dein Countdown. Kostenlos am Handgelenk.'],['Dienstplan · Feiertage','Dein Monat.|Alles im Blick.','Schicht ändern. Direkt im Kalender sehen.|Regionale Feiertage bei Bedarf aktivieren.'],['Rückblick · Jahresansicht mit DoneAt Plus','Dein Arbeitsjahr.|In Farbe.','Arbeitsstunden im Jahresüberblick.|Entdecke deinen Rhythmus.'],['Pomodoro · DoneAt Plus','Zeit für Fokus.|Zeit für Pausen.','Plane Aufgaben in deine Fokuszeiten ein.|Und lass Raum für Erholung.'],['Immer im Blick','Auch ohne|Öffnen der App.','Dynamic Island · Sperrbildschirm · Widgets'],['Raum für Erholung','Pause bleibt|Pause.','Pausen zählen nicht zur Arbeitszeit.']],['Projektnotizen prüfen','Entwurf ausarbeiten','E-Mails beantworten']),
 fr:set('fr-FR','fr','Enfin|du temps|pour vous.',81,'Votre temps ne se résume|pas au travail.','Utilisation gratuite',[
 ['Chaque seconde vous rapproche de la sortie.',''],['Aussi sur Apple Watch','Un regard.|Bientôt libre.','Le compte à rebours, gratuit à votre poignet.'],['Planning · Jours fériés','Votre mois.|En un regard.','Modifiez un horaire, le calendrier suit.|Activez les jours fériés de votre région.'],['Historique · Vue annuelle DoneAt Plus','Votre année|en couleurs.','Retrouvez vos heures de travail.|Découvrez votre rythme.'],['Pomodoro · DoneAt Plus','Se concentrer.|Puis souffler.','Réservez des créneaux à vos tâches.|Gardez aussi du temps pour les pauses.'],['Toujours visible','Même sans|ouvrir l’app.','Dynamic Island · Écran verrouillé · Widgets'],['Une place pour les pauses','Les pauses|restent des pauses.','Les pauses sont déduites du temps de travail.']],['Relire les notes','Préparer le projet','Répondre aux e-mails']),
 es:set('es-ES','es','Ya casi|es tu|hora.',98,'Tu tiempo no es|solo para trabajar.','Uso gratuito',[
 ['Cada segundo, más cerca de salir.',''],['Ahora en Apple Watch','Mira tu muñeca.|Ya queda menos.','Tu cuenta atrás, gratis en la muñeca.'],['Turnos · Festivos','Tu mes,|de un vistazo.','Cambia un turno y míralo en el calendario.|Activa los festivos de tu región.'],['Registros · Vista anual con DoneAt Plus','Tu año laboral,|en colores.','Repasa tus horas de trabajo.|Descubre tu propio ritmo.'],['Pomodoro · DoneAt Plus','Hora de centrarte.|Hora de descansar.','Reserva tiempo para tus tareas.|Y deja espacio para las pausas.'],['Siempre a la vista','Sin abrir|la app.','Dynamic Island · Pantalla bloqueada · Widgets'],['Haz sitio al descanso','Las pausas|no son trabajo.','Las pausas se descuentan de tus horas.']],['Revisar las notas','Preparar la propuesta','Responder correos']),
 it:set('it','it','Tra poco,|il tempo|è tuo.',84,'Il tuo tempo non è|solo lavoro.','Gratis',[
 ['Ogni secondo, più vicino alla fine del turno.',''],['Ora anche su Apple Watch','Uno sguardo.|Manca meno.','Il conto alla rovescia, gratis al polso.'],['Turni · Festività','Il tuo mese.|A colpo d’occhio.','Modifica un turno e vedilo nel calendario.|Attiva le festività della tua regione.'],['Registro · Vista annuale DoneAt Plus','Un anno di lavoro,|a colori.','Ritrova le tue ore di lavoro.|Scopri il tuo ritmo.'],['Pomodoro · DoneAt Plus','Concentrati.|Poi fai una pausa.','Dedica uno spazio alle tue attività.|E lascia spazio alle pause.'],['Sempre visibile','Anche senza|aprire l’app.','Dynamic Island · Schermata di blocco · Widget'],['Spazio alle pause','Le pause|non sono lavoro.','Le pause sono escluse dalle ore lavorate.']],['Rivedere gli appunti','Preparare la proposta','Rispondere alle email']),
 pt:set('pt-BR','pt','Já já,|o tempo|é seu.',96,'Seu tempo vai além|do trabalho.','Uso gratuito',[
 ['A cada segundo, mais perto de sair.',''],['Agora no Apple Watch','Olhe o pulso.|Falta menos.','Sua contagem regressiva, grátis no pulso.'],['Escala · Feriados','Seu mês.|Num olhar.','Mude um turno e veja no calendário.|Ative os feriados da sua região.'],['Registros · Visão anual com DoneAt Plus','Seu trabalho,|em cores.','Reveja suas horas de trabalho.|Encontre seu ritmo.'],['Pomodoro · DoneAt Plus','Hora de focar.|Hora de pausar.','Reserve tempo para suas tarefas.|E deixe espaço para as pausas.'],['Sempre à vista','Sem abrir|o app.','Dynamic Island · Tela Bloqueada · Widgets'],['Espaço para descansar','Pausa não é|hora trabalhada.','As pausas ficam fora das horas de trabalho.']],['Revisar as anotações','Preparar a proposta','Responder aos e-mails']),
 ja:set('ja','ja','仕事の|あとは、|自分時間。',79,'仕事だけじゃない。|自分の時間も、大切に。','無料で使えます',[
 ['一秒ずつ、退勤へ。',''],['Apple Watch でも','手首を見る。|退勤が近づく。','退勤までの時間を、手首で無料チェック。'],['シフト · 祝日','今月の予定を、|ひと目で。','変更したシフトが、すぐカレンダーに。|地域の祝日テンプレートも設定できます。'],['記録 · DoneAt Plus 年表示','働いた日々を、|色で振り返る。','一年の労働時間を見渡して、|自分のリズムを見つけよう。'],['ポモドーロ · DoneAt Plus','集中する時間。|ひと息つく時間。','タスクを集中時間に割り当てて、|休憩の時間も大切に。'],['いつでも見える','開かなくても、|あと何分。','Dynamic Island · ロック画面 · ウィジェット'],['休憩の時間を大切に','休憩は、|仕事に含めない。','休憩を差し引いた時間でカウントダウン。']],['資料を確認する','企画書をまとめる','メールに返信する']),
 ko:set('ko','ko','퇴근 뒤엔,|나만의|시간.',80,'일을 마치고,|나를 위한 시간으로.','무료로 사용',[
 ['매초, 퇴근에 한 걸음 더 가까이.',''],['이제 Apple Watch에서도','손목에서 확인.|퇴근이 가까워져요.','퇴근 카운트다운을 손목에서 무료로.'],['근무 일정 · 공휴일','이번 달 일정,|한눈에.','근무를 바꾸면 달력에 바로 반영돼요.|지역 공휴일 템플릿도 켤 수 있어요.'],['기록 · DoneAt Plus 연간 보기','일한 날들을,|색으로 돌아봐요.','일 년의 근무 시간을 살펴보고,|나만의 리듬을 찾아보세요.'],['뽀모도로 · DoneAt Plus','집중할 시간.|쉬어 갈 시간.','할 일을 집중 시간에 배치하고,|휴식 시간도 챙겨 보세요.'],['언제든 확인','앱을 열지 않아도,|남은 시간이 보여요.','Dynamic Island · 잠금 화면 · 위젯'],['휴식에도 여유를','휴식 시간은,|근무 시간에서 빼요.','휴식을 제외한 실제 근무 시간으로 계산해요.']],['프로젝트 자료 검토','제안서 작성','이메일 답장']),
 ru:set('ru','ru','Скоро —|время|для себя.',82,'Ваше время —|не только для работы.','Бесплатно',[
 ['Каждая секунда приближает конец смены.',''],['Теперь и на Apple Watch','Взгляд на часы.|Скоро домой.','Обратный отсчёт на запястье. Бесплатно.'],['График · Праздники','Ваш месяц.|Всё перед глазами.','Меняйте смены прямо в календаре.|Подключите праздники своего региона.'],['История · Годовой обзор DoneAt Plus','Год работы.|В цвете.','Посмотрите на свои рабочие часы.|Найдите свой ритм.'],['Помодоро · DoneAt Plus','Время работать.|Время отдыхать.','Выделите время для задач.|И оставьте место для перерывов.'],['Всегда на виду','Без запуска|приложения.','Dynamic Island · Экран блокировки · Виджеты'],['Место для отдыха','Перерыв —|не рабочее время.','Перерывы исключаются из рабочих часов.']],['Изучить материалы','Подготовить проект','Ответить на письма']),
 tr:set('tr','tr','Az kaldı.|Zaman|senin.',90,'Zamanın sadece|iş için değil.','Ücretsiz kullanım',[
 ['Her saniye, mesai sonuna biraz daha yakın.',''],['Artık Apple Watch’ta','Bileğine bak.|Az kaldı.','Mesai sayacı, bileğinde ve ücretsiz.'],['Vardiyalar · Resmî tatiller','Ayın tamamı.|Bir bakışta.','Vardiyayı değiştir, takvimde hemen gör.|Bölgenin tatil şablonunu etkinleştir.'],['Kayıtlar · DoneAt Plus yıllık görünüm','Çalıştığın günler,|renklerle.','Bir yıllık çalışma saatlerine bak.|Kendi ritmini bul.'],['Pomodoro · DoneAt Plus','Odaklan.|Sonra mola ver.','Görevlerine zaman ayır.|Molalara da yer bırak.'],['Her zaman görünür','Uygulamayı|açmadan da gör.','Dynamic Island · Kilit Ekranı · Araç Takımları'],['Molalara yer aç','Mola süresi,|işten sayılmaz.','Molalar çalışma süresinden düşülür.']],['Proje notlarını incele','Teklifi hazırla','E-postaları yanıtla']),
 id:set('id','id','Sebentar|lagi,|waktumu.',86,'Waktumu bukan|hanya untuk bekerja.','Gratis digunakan',[
 ['Setiap detik, makin dekat waktu pulang.',''],['Kini di Apple Watch','Lihat pergelangan.|Sebentar lagi.','Hitung mundur kerja, gratis di pergelangan.'],['Jadwal · Hari libur','Sebulan penuh.|Sekilas saja.','Ubah sif, langsung terlihat di kalender.|Aktifkan templat hari libur wilayahmu.'],['Catatan · Tampilan tahunan DoneAt Plus','Setahun bekerja,|dalam warna.','Lihat kembali jam kerjamu.|Temukan ritmemu.'],['Pomodoro · DoneAt Plus','Saatnya fokus.|Saatnya jeda.','Beri tugasmu tempat dalam jadwal.|Sisakan juga waktu untuk istirahat.'],['Selalu terlihat','Tanpa membuka|aplikasi.','Dynamic Island · Layar Terkunci · Widget'],['Ruang untuk istirahat','Istirahat bukan|jam kerja.','Waktu istirahat tidak dihitung sebagai kerja.']],['Tinjau catatan proyek','Susun proposal','Balas email']),
 vi:set('vi','vi','Sắp đến|giờ của|riêng bạn.',78,'Thời gian của bạn|không chỉ dành cho công việc.','Sử dụng miễn phí',[
 ['Mỗi giây, gần giờ tan làm hơn.',''],['Nay có trên Apple Watch','Nhìn cổ tay.|Sắp tan làm.','Đếm ngược tan làm, miễn phí trên cổ tay.'],['Lịch làm việc · Ngày lễ','Cả tháng,|trong một cái nhìn.','Đổi ca là thấy ngay trên lịch.|Bật mẫu ngày lễ cho khu vực của bạn.'],['Lịch sử · Xem theo năm với DoneAt Plus','Một năm làm việc,|qua sắc màu.','Nhìn lại những giờ đã làm.|Tìm nhịp điệu của riêng bạn.'],['Pomodoro · DoneAt Plus','Lúc tập trung.|Lúc nghỉ ngơi.','Xếp việc cần làm vào phiên tập trung.|Và dành chỗ cho những giờ nghỉ.'],['Luôn trong tầm mắt','Không cần|mở ứng dụng.','Dynamic Island · Màn hình khóa · Tiện ích'],['Dành chỗ cho giờ nghỉ','Giờ nghỉ|không tính giờ làm.','Tự động trừ thời gian nghỉ khỏi giờ làm.']],['Xem tài liệu dự án','Soạn đề xuất','Trả lời email']),
 th:set('th','th','ใกล้ถึง|เวลาของ|คุณแล้ว',82,'เวลาของคุณ|ไม่ได้มีไว้แค่ทำงาน','ใช้งานฟรี',[
 ['ทุกวินาที ใกล้เวลาเลิกงานอีกนิด',''],['พร้อมใช้บน Apple Watch','ดูที่ข้อมือ|ใกล้เลิกงานแล้ว','นับถอยหลังเลิกงานบนข้อมือ ใช้ฟรี'],['ตารางงาน · วันหยุด','ตารางทั้งเดือน|เห็นได้ในพริบตา','เปลี่ยนกะ แล้วเห็นในปฏิทินทันที|เปิดแม่แบบวันหยุดของภูมิภาคคุณได้'],['บันทึก · มุมมองรายปีใน DoneAt Plus','หนึ่งปีที่ทำงาน|มองผ่านสีสัน','ย้อนดูชั่วโมงทำงานของคุณ|แล้วค้นหาจังหวะที่ใช่'],['โพโมโดโร · DoneAt Plus','เวลาจดจ่อ|เวลาพัก','จัดงานลงในช่วงเวลาจดจ่อ|และเผื่อเวลาไว้พักด้วย'],['เห็นได้เสมอ','ไม่ต้องเปิดแอป|ก็ดูได้','Dynamic Island · หน้าจอล็อค · วิดเจ็ต'],['เว้นที่ว่างให้การพัก','เวลาพัก|ไม่นับเป็นงาน','หักเวลาพักออกจากชั่วโมงทำงานอัตโนมัติ']],['ทบทวนข้อมูลโครงการ','ร่างข้อเสนอ','ตอบอีเมล']),
 'hi-IN':set('hi','hi','बस कुछ पल,|फिर वक़्त|आपका।',76,'काम के बाद,|थोड़ा समय अपने लिए।','मुफ़्त इस्तेमाल करें',[
 ['हर सेकंड, छुट्टी के और करीब।',''],['अब Apple Watch पर भी','कलाई पर देखें।|छुट्टी करीब है।','काम की उलटी गिनती, कलाई पर मुफ़्त।'],['शेड्यूल · छुट्टियाँ','पूरे महीने का प्लान,|एक नज़र में।','शिफ़्ट बदलें, कैलेंडर में तुरंत देखें।|अपने क्षेत्र की छुट्टियों का टेम्पलेट चालू करें।'],['रिकॉर्ड · DoneAt Plus में साल का नज़ारा','साल भर का काम,|रंगों में देखें।','अपने काम के घंटों पर नज़र डालें।|अपनी लय पहचानें।'],['पोमोडोरो · DoneAt Plus','ध्यान लगाने का वक़्त।|फिर थोड़ा आराम।','अपने कामों के लिए फ़ोकस समय तय करें।|और ब्रेक के लिए भी जगह रखें।'],['हमेशा नज़र में','ऐप खोले बिना|भी देखें।','Dynamic Island · लॉक स्क्रीन · विजेट'],['आराम के लिए जगह','ब्रेक का समय,|काम में नहीं।','ब्रेक काम के घंटों से अपने आप घट जाते हैं।']],['प्रोजेक्ट नोट्स देखें','प्रस्ताव तैयार करें','ईमेल के जवाब दें']),
 ar:set('ar-SA','ar','اقترب|وقتك|الخاص.',100,'وقتك ليس|للعمل فقط.','استخدام مجاني',[
 ['كل ثانية تقرّبك من نهاية الدوام.',''],['الآن على Apple Watch','نظرة لمعصمك.|اقترب وقتك.','العدّ التنازلي للدوام، مجانًا على معصمك.'],['جدول العمل · العطلات','شهرك كاملًا.|بنظرة واحدة.','غيّر الوردية، وشاهدها فورًا في التقويم.|فعّل قالب العطلات الخاص بمنطقتك.'],['السجلات · العرض السنوي مع DoneAt Plus','عام من العمل،|بالألوان.','راجع ساعات عملك على مدار السنة.|واكتشف إيقاعك الخاص.'],['بومودورو · DoneAt Plus','وقت للتركيز.|ووقت للراحة.','خصّص فترات تركيز لمهامك.|واترك مساحة للاستراحة أيضًا.'],['أمامك دائمًا','دون فتح|التطبيق.','Dynamic Island · شاشة القفل · الأدوات'],['مساحة للاستراحة','وقت الاستراحة|ليس وقت عمل.','تُستثنى الاستراحات من ساعات العمل.']],['مراجعة ملاحظات المشروع','إعداد المقترح','الرد على الرسائل'])
};
export const PAGE_NAMES=['01-countdown','02-countdown-detail','03-watch','04-calendar','05-records','06-focus','07-widgets','08-breaks'];
export const FOOTERS={
'zh-CN':['轻轻一瞥，心里有数。','轻轻一瞥，今天的进度就在眼前。'],
'zh-TW':['輕輕一瞥，心裡有數。','輕輕一瞥，今天的進度就在眼前。'],
en:['A quick glance. You’re up to date.','Your day’s progress, just a glance away.'],
de:['Ein Blick genügt.','Dein Fortschritt. Mit einem Blick.'],
fr:['Un regard, et vous savez.','Votre journée avance, sous vos yeux.'],
es:['Un vistazo y lo sabes.','El progreso del día, de un vistazo.'],
it:['Uno sguardo, e sai.','La tua giornata, a colpo d’occhio.'],
pt:['Um olhar e você já sabe.','Seu progresso no dia, num olhar.'],
ja:['ちらっと見るだけ。あと少し。','今日の進み具合を、ひと目で。'],
ko:['한 번 보면 알 수 있어요.','오늘의 진행 상황을 한눈에.'],
ru:['Одного взгляда достаточно.','Ваш день — перед глазами.'],
tr:['Bir bakış yeter.','Günün ilerleyişi, bir bakışta.'],
id:['Sekilas, langsung tahu.','Lihat progres harimu dalam sekejap.'],
vi:['Liếc nhìn là biết.','Tiến độ hôm nay, chỉ một cái nhìn.'],
th:['มองแวบเดียวก็รู้','ความคืบหน้าวันนี้ เห็นได้ในพริบตา'],
'hi-IN':['एक नज़र, और सब साफ़।','आज की प्रगति, एक नज़र में।'],
ar:['نظرة واحدة تكفي.','تقدّم يومك، بنظرة واحدة.']};
