// Generated by scripts/generate-watch-localizations.mjs. Do not edit.
import Foundation

nonisolated enum WatchLocalizations {
    private static let values: [String: [String: String]] = [
        "en": [
            "watchWaitingForIPhone": "Waiting for iPhone",
            "watchConfirmPlusOnIPhone": "Confirm Plus on your iPhone.",
            "watchSyncExpired": "The last update expired.",
            "watchOpenIPhone": "Open DoneAt on your iPhone.",
            "watchTimeLeftTitle": "Time left",
            "watchTimeLeft": "{{duration}} left",
            "watchOffAt": "Off at {{time}}",
            "watchOvertimeUntil": "Overtime until {{time}}",
            "watchBackAt": "Back at {{time}}",
            "watchNextShiftAt": "Next shift {{time}}",
            "watchPlusIncludes": "Complications and full shift status are included in DoneAt Plus.",
            "watchPlusOnIPhone": "See plans on your iPhone. The countdown Live Activity in the Smart Stack stays free.",
            "watchWidgetDescription": "Time left and progress until you're off work."
        ],
        "zh-CN": [
            "watchWaitingForIPhone": "正在等待 iPhone",
            "watchConfirmPlusOnIPhone": "请在 iPhone 上确认 Plus 状态。",
            "watchSyncExpired": "上次同步的数据已过期。",
            "watchOpenIPhone": "请在 iPhone 上打开 DoneAt。",
            "watchTimeLeftTitle": "剩余时间",
            "watchTimeLeft": "剩余 {{duration}}",
            "watchOffAt": "{{time}} 下班",
            "watchOvertimeUntil": "加班至 {{time}}",
            "watchBackAt": "{{time}} 继续工作",
            "watchNextShiftAt": "下一班 {{time}}",
            "watchPlusIncludes": "表盘复杂功能和完整班次状态包含在 DoneAt Plus 中。",
            "watchPlusOnIPhone": "请在 iPhone 上查看方案。智能叠放里的倒计时实时活动仍可免费使用。",
            "watchWidgetDescription": "查看距离下班的剩余时间和进度。"
        ],
        "zh-HK": [
            "watchWaitingForIPhone": "正在等候 iPhone",
            "watchConfirmPlusOnIPhone": "請在 iPhone 上確認 Plus 狀態。",
            "watchSyncExpired": "上次同步的資料已過期。",
            "watchOpenIPhone": "請在 iPhone 上開啟 DoneAt。",
            "watchTimeLeftTitle": "剩餘時間",
            "watchTimeLeft": "剩餘 {{duration}}",
            "watchOffAt": "{{time}} 下班",
            "watchOvertimeUntil": "加班至 {{time}}",
            "watchBackAt": "{{time}} 繼續工作",
            "watchNextShiftAt": "下一更 {{time}}",
            "watchPlusIncludes": "錶面複雜功能和完整班次狀態包含喺 DoneAt Plus 入面。",
            "watchPlusOnIPhone": "請喺 iPhone 上查看方案。智慧型疊放中嘅倒數即時動態仍可免費使用。",
            "watchWidgetDescription": "查看距離下班嘅剩餘時間同進度。"
        ],
        "zh-TW": [
            "watchWaitingForIPhone": "正在等候 iPhone",
            "watchConfirmPlusOnIPhone": "請在 iPhone 上確認 Plus 狀態。",
            "watchSyncExpired": "上次同步的資料已過期。",
            "watchOpenIPhone": "請在 iPhone 上開啟 DoneAt。",
            "watchTimeLeftTitle": "剩餘時間",
            "watchTimeLeft": "剩餘 {{duration}}",
            "watchOffAt": "{{time}} 下班",
            "watchOvertimeUntil": "加班至 {{time}}",
            "watchBackAt": "{{time}} 繼續工作",
            "watchNextShiftAt": "下一班 {{time}}",
            "watchPlusIncludes": "錶面複雜功能和完整班次狀態包含在 DoneAt Plus 中。",
            "watchPlusOnIPhone": "請在 iPhone 上查看方案。智慧型疊放中的倒數即時動態仍可免費使用。",
            "watchWidgetDescription": "查看距離下班的剩餘時間和進度。"
        ],
        "ja": [
            "watchWaitingForIPhone": "iPhoneを待っています",
            "watchConfirmPlusOnIPhone": "iPhoneでPlusの状態を確認してください。",
            "watchSyncExpired": "前回の同期データは期限切れです。",
            "watchOpenIPhone": "iPhoneでDoneAtを開いてください。",
            "watchTimeLeftTitle": "残り時間",
            "watchTimeLeft": "残り {{duration}}",
            "watchOffAt": "{{time}}に退勤",
            "watchOvertimeUntil": "{{time}} まで残業",
            "watchBackAt": "{{time}}に復帰",
            "watchNextShiftAt": "次の勤務は{{time}}",
            "watchPlusIncludes": "コンプリケーションと完全な勤務状況はDoneAt Plusに含まれます。",
            "watchPlusOnIPhone": "プランはiPhoneでご確認ください。スマートスタックでのカウントダウンのライブアクティビティは無料のままです。",
            "watchWidgetDescription": "退勤までの残り時間と進捗。"
        ],
        "ko": [
            "watchWaitingForIPhone": "iPhone을 기다리는 중",
            "watchConfirmPlusOnIPhone": "iPhone에서 Plus 상태를 확인하세요.",
            "watchSyncExpired": "마지막 동기화 데이터가 만료되었습니다.",
            "watchOpenIPhone": "iPhone에서 DoneAt을 여세요.",
            "watchTimeLeftTitle": "남은 시간",
            "watchTimeLeft": "{{duration}} 남음",
            "watchOffAt": "{{time}}에 퇴근",
            "watchOvertimeUntil": "{{time}}까지 연장 근무",
            "watchBackAt": "{{time}}에 복귀",
            "watchNextShiftAt": "다음 근무 {{time}}",
            "watchPlusIncludes": "컴플리케이션과 전체 근무 상태는 DoneAt Plus에 포함됩니다.",
            "watchPlusOnIPhone": "iPhone에서 요금제를 확인하세요. 스마트 스택의 카운트다운 실시간 액티비티는 계속 무료로 제공됩니다.",
            "watchWidgetDescription": "퇴근까지 남은 시간과 진행률."
        ],
        "de": [
            "watchWaitingForIPhone": "Warten auf das iPhone",
            "watchConfirmPlusOnIPhone": "Bestätige Plus auf deinem iPhone.",
            "watchSyncExpired": "Die letzte Aktualisierung ist abgelaufen.",
            "watchOpenIPhone": "Öffne DoneAt auf deinem iPhone.",
            "watchTimeLeftTitle": "Verbleibende Zeit",
            "watchTimeLeft": "Noch {{duration}}",
            "watchOffAt": "Feierabend um {{time}}",
            "watchOvertimeUntil": "Überstunden bis {{time}}",
            "watchBackAt": "Zurück um {{time}}",
            "watchNextShiftAt": "Nächste Schicht um {{time}}",
            "watchPlusIncludes": "Komplikationen und der vollständige Schichtstatus gehören zu DoneAt Plus.",
            "watchPlusOnIPhone": "Sieh dir die Pläne auf deinem iPhone an. Die Live-Aktivität des Countdowns im Smart-Stapel bleibt kostenlos.",
            "watchWidgetDescription": "Verbleibende Zeit und Fortschritt bis zum Feierabend."
        ],
        "es": [
            "watchWaitingForIPhone": "Esperando al iPhone",
            "watchConfirmPlusOnIPhone": "Confirma Plus en tu iPhone.",
            "watchSyncExpired": "La última actualización ha caducado.",
            "watchOpenIPhone": "Abre DoneAt en tu iPhone.",
            "watchTimeLeftTitle": "Tiempo restante",
            "watchTimeLeft": "Quedan {{duration}}",
            "watchOffAt": "Salida a las {{time}}",
            "watchOvertimeUntil": "Horas extra hasta las {{time}}",
            "watchBackAt": "Vuelta a las {{time}}",
            "watchNextShiftAt": "Próximo turno a las {{time}}",
            "watchPlusIncludes": "Las complicaciones y el estado completo del turno están incluidos en DoneAt Plus.",
            "watchPlusOnIPhone": "Consulta los planes en tu iPhone. La actividad en vivo de la cuenta atrás en el grupo inteligente sigue siendo gratis.",
            "watchWidgetDescription": "Tiempo restante y progreso hasta la hora de salida."
        ],
        "fr": [
            "watchWaitingForIPhone": "En attente de l’iPhone",
            "watchConfirmPlusOnIPhone": "Confirmez Plus sur votre iPhone.",
            "watchSyncExpired": "La dernière mise à jour a expiré.",
            "watchOpenIPhone": "Ouvrez DoneAt sur votre iPhone.",
            "watchTimeLeftTitle": "Temps restant",
            "watchTimeLeft": "Encore {{duration}}",
            "watchOffAt": "Départ à {{time}}",
            "watchOvertimeUntil": "Heures sup. jusqu'à {{time}}",
            "watchBackAt": "Retour à {{time}}",
            "watchNextShiftAt": "Prochain service à {{time}}",
            "watchPlusIncludes": "Les complications et le statut complet du service sont inclus dans DoneAt Plus.",
            "watchPlusOnIPhone": "Consultez les formules sur votre iPhone. L’activité en direct du compte à rebours dans le Défilement intelligent reste gratuite.",
            "watchWidgetDescription": "Temps restant et progression jusqu’au départ."
        ],
        "it": [
            "watchWaitingForIPhone": "In attesa di iPhone",
            "watchConfirmPlusOnIPhone": "Conferma Plus sul tuo iPhone.",
            "watchSyncExpired": "L’ultimo aggiornamento è scaduto.",
            "watchOpenIPhone": "Apri DoneAt sul tuo iPhone.",
            "watchTimeLeftTitle": "Tempo rimanente",
            "watchTimeLeft": "Restano {{duration}}",
            "watchOffAt": "Uscita alle {{time}}",
            "watchOvertimeUntil": "Straordinario fino alle {{time}}",
            "watchBackAt": "Rientro alle {{time}}",
            "watchNextShiftAt": "Prossimo turno alle {{time}}",
            "watchPlusIncludes": "Le complicazioni e lo stato completo del turno sono inclusi in DoneAt Plus.",
            "watchPlusOnIPhone": "Consulta i piani sul tuo iPhone. L’attività in tempo reale del conto alla rovescia nella raccolta smart resta gratuita.",
            "watchWidgetDescription": "Tempo rimanente e avanzamento fino all’uscita."
        ],
        "pt": [
            "watchWaitingForIPhone": "Aguardando o iPhone",
            "watchConfirmPlusOnIPhone": "Confirme o Plus no iPhone.",
            "watchSyncExpired": "A última atualização expirou.",
            "watchOpenIPhone": "Abra o DoneAt no iPhone.",
            "watchTimeLeftTitle": "Tempo restante",
            "watchTimeLeft": "Faltam {{duration}}",
            "watchOffAt": "Saída às {{time}}",
            "watchOvertimeUntil": "Hora extra até {{time}}",
            "watchBackAt": "De volta às {{time}}",
            "watchNextShiftAt": "Próximo turno às {{time}}",
            "watchPlusIncludes": "As complicações e o status completo do turno estão incluídos no DoneAt Plus.",
            "watchPlusOnIPhone": "Veja os planos no seu iPhone. A Atividade ao Vivo da contagem regressiva no Conjunto Inteligente continua gratuita.",
            "watchWidgetDescription": "Tempo restante e progresso até a saída."
        ],
        "ru": [
            "watchWaitingForIPhone": "Ожидание iPhone",
            "watchConfirmPlusOnIPhone": "Подтвердите Plus на iPhone.",
            "watchSyncExpired": "Последнее обновление устарело.",
            "watchOpenIPhone": "Откройте DoneAt на iPhone.",
            "watchTimeLeftTitle": "Оставшееся время",
            "watchTimeLeft": "Осталось {{duration}}",
            "watchOffAt": "Конец работы в {{time}}",
            "watchOvertimeUntil": "Переработка до {{time}}",
            "watchBackAt": "Обратно в {{time}}",
            "watchNextShiftAt": "Следующая смена в {{time}}",
            "watchPlusIncludes": "Расширения и полный статус смены включены в DoneAt Plus.",
            "watchPlusOnIPhone": "Смотрите тарифы на iPhone. Live-активность обратного отсчёта в смарт-стопке остаётся бесплатной.",
            "watchWidgetDescription": "Оставшееся время и прогресс до конца работы."
        ],
        "ar": [
            "watchWaitingForIPhone": "بانتظار iPhone",
            "watchConfirmPlusOnIPhone": "أكّد حالة Plus على iPhone.",
            "watchSyncExpired": "انتهت صلاحية آخر تحديث.",
            "watchOpenIPhone": "افتح DoneAt على iPhone.",
            "watchTimeLeftTitle": "الوقت المتبقي",
            "watchTimeLeft": "بقي {{duration}}",
            "watchOffAt": "الانصراف عند {{time}}",
            "watchOvertimeUntil": "عمل إضافي حتى {{time}}",
            "watchBackAt": "العودة عند {{time}}",
            "watchNextShiftAt": "الوردية التالية عند {{time}}",
            "watchPlusIncludes": "الإضافات وحالة الوردية الكاملة متضمّنة في DoneAt Plus.",
            "watchPlusOnIPhone": "اطّلع على الخطط على iPhone. يبقى النشاط المباشر للعد التنازلي في الحزمة المكدسة الذكية مجانيًا.",
            "watchWidgetDescription": "الوقت المتبقي والتقدم حتى الانصراف."
        ],
        "hi-IN": [
            "watchWaitingForIPhone": "iPhone की प्रतीक्षा हो रही है",
            "watchConfirmPlusOnIPhone": "अपने iPhone पर Plus की पुष्टि करें।",
            "watchSyncExpired": "पिछला अपडेट समाप्त हो गया है।",
            "watchOpenIPhone": "अपने iPhone पर DoneAt खोलें।",
            "watchTimeLeftTitle": "बचा समय",
            "watchTimeLeft": "{{duration}} बचा",
            "watchOffAt": "{{time}} पर छुट्टी",
            "watchOvertimeUntil": "{{time}} तक ओवरटाइम",
            "watchBackAt": "{{time}} पर वापसी",
            "watchNextShiftAt": "अगली शिफ़्ट {{time}} पर",
            "watchPlusIncludes": "कॉम्प्लिकेशन और पूरी शिफ़्ट स्थिति DoneAt Plus में शामिल हैं।",
            "watchPlusOnIPhone": "अपने iPhone पर प्लान देखें। स्मार्ट स्टैक में काउंटडाउन की लाइव ऐक्टिविटी मुफ़्त बनी रहती है।",
            "watchWidgetDescription": "छुट्टी तक बचा समय और प्रगति।"
        ],
        "mr-IN": [
            "watchWaitingForIPhone": "iPhone ची प्रतीक्षा सुरू आहे",
            "watchConfirmPlusOnIPhone": "तुमच्या iPhone वर Plus ची पुष्टी करा.",
            "watchSyncExpired": "मागील अपडेटची मुदत संपली आहे.",
            "watchOpenIPhone": "तुमच्या iPhone वर DoneAt उघडा.",
            "watchTimeLeftTitle": "उरलेला वेळ",
            "watchTimeLeft": "{{duration}} उरले",
            "watchOffAt": "{{time}} ला सुट्टी",
            "watchOvertimeUntil": "{{time}} पर्यंत ओव्हरटाइम",
            "watchBackAt": "{{time}} ला परत",
            "watchNextShiftAt": "पुढील शिफ्ट {{time}} ला",
            "watchPlusIncludes": "कॉम्प्लिकेशन आणि संपूर्ण शिफ्ट स्थिती DoneAt Plus मध्ये समाविष्ट आहेत.",
            "watchPlusOnIPhone": "तुमच्या iPhone वर प्लॅन पाहा. स्मार्ट स्टॅकमधील काउंटडाउनची लाइव्ह ॲक्टिव्हिटी मोफतच राहते.",
            "watchWidgetDescription": "सुट्टीपर्यंत उरलेला वेळ आणि प्रगती."
        ],
        "id": [
            "watchWaitingForIPhone": "Menunggu iPhone",
            "watchConfirmPlusOnIPhone": "Konfirmasikan Plus di iPhone Anda.",
            "watchSyncExpired": "Pembaruan terakhir telah kedaluwarsa.",
            "watchOpenIPhone": "Buka DoneAt di iPhone Anda.",
            "watchTimeLeftTitle": "Sisa waktu",
            "watchTimeLeft": "Sisa {{duration}}",
            "watchOffAt": "Pulang pukul {{time}}",
            "watchOvertimeUntil": "Lembur sampai {{time}}",
            "watchBackAt": "Kembali pukul {{time}}",
            "watchNextShiftAt": "Sif berikutnya pukul {{time}}",
            "watchPlusIncludes": "Komplikasi dan status sif lengkap sudah termasuk dalam DoneAt Plus.",
            "watchPlusOnIPhone": "Lihat paket di iPhone Anda. Live Activity hitung mundur di Smart Stack tetap gratis.",
            "watchWidgetDescription": "Sisa waktu dan kemajuan sampai pulang."
        ],
        "th": [
            "watchWaitingForIPhone": "กำลังรอ iPhone",
            "watchConfirmPlusOnIPhone": "ยืนยัน Plus บน iPhone ของคุณ",
            "watchSyncExpired": "การอัปเดตล่าสุดหมดอายุแล้ว",
            "watchOpenIPhone": "เปิด DoneAt บน iPhone ของคุณ",
            "watchTimeLeftTitle": "เวลาที่เหลือ",
            "watchTimeLeft": "เหลือ {{duration}}",
            "watchOffAt": "เลิกงาน {{time}}",
            "watchOvertimeUntil": "ทำโอทีถึง {{time}}",
            "watchBackAt": "กลับ {{time}}",
            "watchNextShiftAt": "กะถัดไป {{time}}",
            "watchPlusIncludes": "กลไกหน้าปัดและสถานะกะแบบเต็มรวมอยู่ใน DoneAt Plus",
            "watchPlusOnIPhone": "ดูแพ็กเกจได้ที่ iPhone ของคุณ กิจกรรมสดของตัวนับถอยหลังในวิดเจ็ตซ้อนอัจฉริยะยังคงใช้งานได้ฟรี",
            "watchWidgetDescription": "เวลาที่เหลือและความคืบหน้าจนถึงเวลาเลิกงาน"
        ],
        "tr": [
            "watchWaitingForIPhone": "iPhone bekleniyor",
            "watchConfirmPlusOnIPhone": "Plus durumunu iPhone’unuzda doğrulayın.",
            "watchSyncExpired": "Son güncellemenin süresi doldu.",
            "watchOpenIPhone": "iPhone’unuzda DoneAt’i açın.",
            "watchTimeLeftTitle": "Kalan süre",
            "watchTimeLeft": "{{duration}} kaldı",
            "watchOffAt": "Çıkış: {{time}}",
            "watchOvertimeUntil": "{{time}} saatine kadar mesai",
            "watchBackAt": "Dönüş: {{time}}",
            "watchNextShiftAt": "Sonraki vardiya: {{time}}",
            "watchPlusIncludes": "Komplikasyonlar ve tam vardiya durumu DoneAt Plus’a dahildir.",
            "watchPlusOnIPhone": "Planları iPhone’unuzda görün. Geri sayımın Canlı Etkinliği, Akıllı Gruplama içinde ücretsiz kalmaya devam ediyor.",
            "watchWidgetDescription": "İş çıkışına kadar kalan süre ve ilerleme."
        ],
        "vi": [
            "watchWaitingForIPhone": "Đang chờ iPhone",
            "watchConfirmPlusOnIPhone": "Xác nhận Plus trên iPhone của bạn.",
            "watchSyncExpired": "Bản cập nhật gần nhất đã hết hạn.",
            "watchOpenIPhone": "Mở DoneAt trên iPhone của bạn.",
            "watchTimeLeftTitle": "Thời gian còn lại",
            "watchTimeLeft": "Còn {{duration}}",
            "watchOffAt": "Tan ca lúc {{time}}",
            "watchOvertimeUntil": "Tăng ca đến {{time}}",
            "watchBackAt": "Quay lại lúc {{time}}",
            "watchNextShiftAt": "Ca tiếp theo lúc {{time}}",
            "watchPlusIncludes": "Tổ hợp và trạng thái ca đầy đủ được bao gồm trong DoneAt Plus.",
            "watchPlusOnIPhone": "Xem các gói trên iPhone của bạn. Hoạt động trực tiếp đếm ngược trong Ngăn xếp thông minh vẫn miễn phí.",
            "watchWidgetDescription": "Thời gian còn lại và tiến độ cho đến khi tan ca."
        ]
    ]

    static func text(_ key: String, localeIdentifier: String? = nil) -> String {
        let candidates = localeIdentifier.map { [$0] } ?? Locale.preferredLanguages
        let locale = resolveLocale(candidates)
        return values[locale]?[key] ?? values["en"]?[key] ?? key
    }

    static func resolveLocale(_ candidates: [String]) -> String {
        for raw in candidates {
            let normalized = raw.replacingOccurrences(of: "_", with: "-")
            if let exact = values.keys.first(where: { $0.caseInsensitiveCompare(normalized) == .orderedSame }) { return exact }
            let lower = normalized.lowercased()
            if lower.hasPrefix("zh-hant-hk") || lower.hasPrefix("zh-hk") { return "zh-HK" }
            if lower.hasPrefix("zh-hant") || lower.hasPrefix("zh-tw") { return "zh-TW" }
            if lower.hasPrefix("zh") { return "zh-CN" }
            if let language = values.keys.first(where: {
                lower.hasPrefix($0.lowercased() + "-") || $0.lowercased().hasPrefix(lower + "-")
            }) { return language }
        }
        return "en"
    }
}
