// Generated by scripts/generate-watch-localizations.mjs. Do not edit.
import Foundation

nonisolated enum WatchLocalizations {
    /// Every language the phone can pin, including regional variants whose
    /// table below only stores strings that differ from the parent.
    private static let supported = ["en", "en-GB", "zh-CN", "zh-HK", "zh-TW", "ja", "ko", "de", "es", "es-MX", "fr", "it", "pt", "ru", "ar", "hi-IN", "mr-IN", "id", "th", "tr", "vi"]
    private static let americanEnglishRegions: Set<String> = ["US", "CA", "PH", "LR", "PR", "GU", "AS", "VI", "UM", "MP"]
    private static let latinAmericanRegions: Set<String> = ["419", "MX", "AR", "BO", "BR", "BZ", "CL", "CO", "CR", "CU", "DO", "EC", "GT", "HN", "NI", "PA", "PE", "PR", "PY", "SV", "US", "UY", "VE"]
    private static let values: [String: [String: String]] = [
        "en": [
            "watchCacheCorrupt": "The saved schedule couldn’t be read. Open DoneAt on your iPhone.",
            "watchUpdateRequired": "Update DoneAt on your Apple Watch.",
            "watchWaitingForIPhone": "Waiting for iPhone",
            "watchSyncExpired": "The last update expired.",
            "watchOpenIPhone": "Open DoneAt on your iPhone.",
            "watchTimeLeftTitle": "Time left",
            "watchTimeLeft": "{{duration}} left",
            "watchOffAt": "Off at {{time}}",
            "watchOvertimeUntil": "Overtime until {{time}}",
            "watchBackAt": "Back at {{time}}",
            "watchNextShiftAt": "Next shift {{time}}",
            "watchWidgetDescription": "Time left and progress until you're off work."
        ],
        "en-GB": [
            "watchCacheCorrupt": "The saved rota couldn’t be read. Open DoneAt on your iPhone."
        ],
        "zh-CN": [
            "watchCacheCorrupt": "无法读取已保存的排班。请在 iPhone 上打开 DoneAt。",
            "watchUpdateRequired": "请更新 Apple Watch 上的 DoneAt。",
            "watchWaitingForIPhone": "正在等待 iPhone",
            "watchSyncExpired": "上次同步的数据已过期。",
            "watchOpenIPhone": "请在 iPhone 上打开 DoneAt。",
            "watchTimeLeftTitle": "剩余时间",
            "watchTimeLeft": "剩余 {{duration}}",
            "watchOffAt": "{{time}} 下班",
            "watchOvertimeUntil": "加班至 {{time}}",
            "watchBackAt": "{{time}} 继续工作",
            "watchNextShiftAt": "下一班 {{time}}",
            "watchWidgetDescription": "查看距离下班的剩余时间和进度。"
        ],
        "zh-HK": [
            "watchCacheCorrupt": "無法讀取已儲存的排班。請在 iPhone 上開啟 DoneAt。",
            "watchUpdateRequired": "請更新 Apple Watch 上的 DoneAt。",
            "watchWaitingForIPhone": "正在等候 iPhone",
            "watchSyncExpired": "上次同步的資料已過期。",
            "watchOpenIPhone": "請在 iPhone 上開啟 DoneAt。",
            "watchTimeLeftTitle": "剩餘時間",
            "watchTimeLeft": "剩餘 {{duration}}",
            "watchOffAt": "{{time}} 下班",
            "watchOvertimeUntil": "加班至 {{time}}",
            "watchBackAt": "{{time}} 繼續工作",
            "watchNextShiftAt": "下一更 {{time}}",
            "watchWidgetDescription": "查看距離下班嘅剩餘時間同進度。"
        ],
        "zh-TW": [
            "watchCacheCorrupt": "無法讀取已儲存的排班。請在 iPhone 上開啟 DoneAt。",
            "watchUpdateRequired": "請更新 Apple Watch 上的 DoneAt。",
            "watchWaitingForIPhone": "正在等候 iPhone",
            "watchSyncExpired": "上次同步的資料已過期。",
            "watchOpenIPhone": "請在 iPhone 上開啟 DoneAt。",
            "watchTimeLeftTitle": "剩餘時間",
            "watchTimeLeft": "剩餘 {{duration}}",
            "watchOffAt": "{{time}} 下班",
            "watchOvertimeUntil": "加班至 {{time}}",
            "watchBackAt": "{{time}} 繼續工作",
            "watchNextShiftAt": "下一班 {{time}}",
            "watchWidgetDescription": "查看距離下班的剩餘時間和進度。"
        ],
        "ja": [
            "watchCacheCorrupt": "保存されたシフトを読み込めませんでした。iPhone で DoneAt を開いてください。",
            "watchUpdateRequired": "Apple Watch の DoneAt を更新してください。",
            "watchWaitingForIPhone": "iPhoneを待っています",
            "watchSyncExpired": "前回の同期データは期限切れです。",
            "watchOpenIPhone": "iPhoneでDoneAtを開いてください。",
            "watchTimeLeftTitle": "残り時間",
            "watchTimeLeft": "残り {{duration}}",
            "watchOffAt": "{{time}}に退勤",
            "watchOvertimeUntil": "{{time}} まで残業",
            "watchBackAt": "{{time}}に復帰",
            "watchNextShiftAt": "次の勤務は{{time}}",
            "watchWidgetDescription": "退勤までの残り時間と進捗。"
        ],
        "ko": [
            "watchCacheCorrupt": "저장된 근무 일정을 읽을 수 없습니다. iPhone에서 DoneAt을 여세요.",
            "watchUpdateRequired": "Apple Watch의 DoneAt을 업데이트하세요.",
            "watchWaitingForIPhone": "iPhone을 기다리는 중",
            "watchSyncExpired": "마지막 동기화 데이터가 만료되었습니다.",
            "watchOpenIPhone": "iPhone에서 DoneAt을 여세요.",
            "watchTimeLeftTitle": "남은 시간",
            "watchTimeLeft": "{{duration}} 남음",
            "watchOffAt": "{{time}}에 퇴근",
            "watchOvertimeUntil": "{{time}}까지 연장 근무",
            "watchBackAt": "{{time}}에 복귀",
            "watchNextShiftAt": "다음 근무 {{time}}",
            "watchWidgetDescription": "퇴근까지 남은 시간과 진행률."
        ],
        "de": [
            "watchCacheCorrupt": "Der gespeicherte Dienstplan konnte nicht gelesen werden. Öffne DoneAt auf deinem iPhone.",
            "watchUpdateRequired": "Aktualisiere DoneAt auf deiner Apple Watch.",
            "watchWaitingForIPhone": "Warten auf das iPhone",
            "watchSyncExpired": "Die letzte Aktualisierung ist abgelaufen.",
            "watchOpenIPhone": "Öffne DoneAt auf deinem iPhone.",
            "watchTimeLeftTitle": "Verbleibende Zeit",
            "watchTimeLeft": "Noch {{duration}}",
            "watchOffAt": "Feierabend um {{time}}",
            "watchOvertimeUntil": "Überstunden bis {{time}}",
            "watchBackAt": "Zurück um {{time}}",
            "watchNextShiftAt": "Nächste Schicht um {{time}}",
            "watchWidgetDescription": "Verbleibende Zeit und Fortschritt bis zum Feierabend."
        ],
        "es": [
            "watchCacheCorrupt": "No se pudo leer el horario guardado. Abre DoneAt en tu iPhone.",
            "watchUpdateRequired": "Actualiza DoneAt en tu Apple Watch.",
            "watchWaitingForIPhone": "Esperando al iPhone",
            "watchSyncExpired": "La última actualización ha caducado.",
            "watchOpenIPhone": "Abre DoneAt en tu iPhone.",
            "watchTimeLeftTitle": "Tiempo restante",
            "watchTimeLeft": "Quedan {{duration}}",
            "watchOffAt": "Salida a las {{time}}",
            "watchOvertimeUntil": "Horas extra hasta las {{time}}",
            "watchBackAt": "Vuelta a las {{time}}",
            "watchNextShiftAt": "Próximo turno a las {{time}}",
            "watchWidgetDescription": "Tiempo restante y progreso hasta la hora de salida."
        ],
        "es-MX": [
            "watchCacheCorrupt": "No se pudo leer el rol de turnos guardado. Abre DoneAt en tu iPhone."
        ],
        "fr": [
            "watchCacheCorrupt": "Le planning enregistré est illisible. Ouvrez DoneAt sur votre iPhone.",
            "watchUpdateRequired": "Mettez à jour DoneAt sur votre Apple Watch.",
            "watchWaitingForIPhone": "En attente de l’iPhone",
            "watchSyncExpired": "La dernière mise à jour a expiré.",
            "watchOpenIPhone": "Ouvrez DoneAt sur votre iPhone.",
            "watchTimeLeftTitle": "Temps restant",
            "watchTimeLeft": "Encore {{duration}}",
            "watchOffAt": "Départ à {{time}}",
            "watchOvertimeUntil": "Heures sup. jusqu'à {{time}}",
            "watchBackAt": "Retour à {{time}}",
            "watchNextShiftAt": "Prochain service à {{time}}",
            "watchWidgetDescription": "Temps restant et progression jusqu’au départ."
        ],
        "it": [
            "watchCacheCorrupt": "Impossibile leggere i turni salvati. Apri DoneAt sul tuo iPhone.",
            "watchUpdateRequired": "Aggiorna DoneAt sul tuo Apple Watch.",
            "watchWaitingForIPhone": "In attesa di iPhone",
            "watchSyncExpired": "L’ultimo aggiornamento è scaduto.",
            "watchOpenIPhone": "Apri DoneAt sul tuo iPhone.",
            "watchTimeLeftTitle": "Tempo rimanente",
            "watchTimeLeft": "Restano {{duration}}",
            "watchOffAt": "Uscita alle {{time}}",
            "watchOvertimeUntil": "Straordinario fino alle {{time}}",
            "watchBackAt": "Rientro alle {{time}}",
            "watchNextShiftAt": "Prossimo turno alle {{time}}",
            "watchWidgetDescription": "Tempo rimanente e avanzamento fino all’uscita."
        ],
        "pt": [
            "watchCacheCorrupt": "Não foi possível ler a escala salva. Abra o DoneAt no iPhone.",
            "watchUpdateRequired": "Atualize o DoneAt no Apple Watch.",
            "watchWaitingForIPhone": "Aguardando o iPhone",
            "watchSyncExpired": "A última atualização expirou.",
            "watchOpenIPhone": "Abra o DoneAt no iPhone.",
            "watchTimeLeftTitle": "Tempo restante",
            "watchTimeLeft": "Faltam {{duration}}",
            "watchOffAt": "Saída às {{time}}",
            "watchOvertimeUntil": "Hora extra até {{time}}",
            "watchBackAt": "De volta às {{time}}",
            "watchNextShiftAt": "Próximo turno às {{time}}",
            "watchWidgetDescription": "Tempo restante e progresso até a saída."
        ],
        "ru": [
            "watchCacheCorrupt": "Не удалось прочитать сохранённое расписание. Откройте DoneAt на iPhone.",
            "watchUpdateRequired": "Обновите DoneAt на Apple Watch.",
            "watchWaitingForIPhone": "Ожидание iPhone",
            "watchSyncExpired": "Последнее обновление устарело.",
            "watchOpenIPhone": "Откройте DoneAt на iPhone.",
            "watchTimeLeftTitle": "Оставшееся время",
            "watchTimeLeft": "Осталось {{duration}}",
            "watchOffAt": "Конец работы в {{time}}",
            "watchOvertimeUntil": "Переработка до {{time}}",
            "watchBackAt": "Обратно в {{time}}",
            "watchNextShiftAt": "Следующая смена в {{time}}",
            "watchWidgetDescription": "Оставшееся время и прогресс до конца работы."
        ],
        "ar": [
            "watchCacheCorrupt": "تعذّرت قراءة الجدول المحفوظ. افتح DoneAt على iPhone.",
            "watchUpdateRequired": "حدّث DoneAt على Apple Watch.",
            "watchWaitingForIPhone": "بانتظار iPhone",
            "watchSyncExpired": "انتهت صلاحية آخر تحديث.",
            "watchOpenIPhone": "افتح DoneAt على iPhone.",
            "watchTimeLeftTitle": "الوقت المتبقي",
            "watchTimeLeft": "بقي {{duration}}",
            "watchOffAt": "الانصراف عند {{time}}",
            "watchOvertimeUntil": "عمل إضافي حتى {{time}}",
            "watchBackAt": "العودة عند {{time}}",
            "watchNextShiftAt": "الوردية التالية عند {{time}}",
            "watchWidgetDescription": "الوقت المتبقي والتقدم حتى الانصراف."
        ],
        "hi-IN": [
            "watchCacheCorrupt": "सेव किया गया शेड्यूल पढ़ा नहीं जा सका। अपने iPhone पर DoneAt खोलें।",
            "watchUpdateRequired": "अपने Apple Watch पर DoneAt अपडेट करें।",
            "watchWaitingForIPhone": "iPhone की प्रतीक्षा हो रही है",
            "watchSyncExpired": "पिछला अपडेट समाप्त हो गया है।",
            "watchOpenIPhone": "अपने iPhone पर DoneAt खोलें।",
            "watchTimeLeftTitle": "बचा समय",
            "watchTimeLeft": "{{duration}} बचा",
            "watchOffAt": "{{time}} पर छुट्टी",
            "watchOvertimeUntil": "{{time}} तक ओवरटाइम",
            "watchBackAt": "{{time}} पर वापसी",
            "watchNextShiftAt": "अगली शिफ़्ट {{time}} पर",
            "watchWidgetDescription": "छुट्टी तक बचा समय और प्रगति।"
        ],
        "mr-IN": [
            "watchCacheCorrupt": "जतन केलेले वेळापत्रक वाचता आले नाही. iPhone वर DoneAt उघडा.",
            "watchUpdateRequired": "Apple Watch वर DoneAt अपडेट करा.",
            "watchWaitingForIPhone": "iPhone ची प्रतीक्षा सुरू आहे",
            "watchSyncExpired": "मागील अपडेटची मुदत संपली आहे.",
            "watchOpenIPhone": "तुमच्या iPhone वर DoneAt उघडा.",
            "watchTimeLeftTitle": "उरलेला वेळ",
            "watchTimeLeft": "{{duration}} उरले",
            "watchOffAt": "{{time}} ला सुट्टी",
            "watchOvertimeUntil": "{{time}} पर्यंत ओव्हरटाइम",
            "watchBackAt": "{{time}} ला परत",
            "watchNextShiftAt": "पुढील शिफ्ट {{time}} ला",
            "watchWidgetDescription": "सुट्टीपर्यंत उरलेला वेळ आणि प्रगती."
        ],
        "id": [
            "watchCacheCorrupt": "Jadwal tersimpan tidak dapat dibaca. Buka DoneAt di iPhone.",
            "watchUpdateRequired": "Perbarui DoneAt di Apple Watch.",
            "watchWaitingForIPhone": "Menunggu iPhone",
            "watchSyncExpired": "Pembaruan terakhir telah kedaluwarsa.",
            "watchOpenIPhone": "Buka DoneAt di iPhone Anda.",
            "watchTimeLeftTitle": "Sisa waktu",
            "watchTimeLeft": "Sisa {{duration}}",
            "watchOffAt": "Pulang pukul {{time}}",
            "watchOvertimeUntil": "Lembur sampai {{time}}",
            "watchBackAt": "Kembali pukul {{time}}",
            "watchNextShiftAt": "Sif berikutnya pukul {{time}}",
            "watchWidgetDescription": "Sisa waktu dan kemajuan sampai pulang."
        ],
        "th": [
            "watchCacheCorrupt": "อ่านตารางงานที่บันทึกไว้ไม่ได้ โปรดเปิด DoneAt บน iPhone",
            "watchUpdateRequired": "โปรดอัปเดต DoneAt บน Apple Watch",
            "watchWaitingForIPhone": "กำลังรอ iPhone",
            "watchSyncExpired": "การอัปเดตล่าสุดหมดอายุแล้ว",
            "watchOpenIPhone": "เปิด DoneAt บน iPhone ของคุณ",
            "watchTimeLeftTitle": "เวลาที่เหลือ",
            "watchTimeLeft": "เหลือ {{duration}}",
            "watchOffAt": "เลิกงาน {{time}}",
            "watchOvertimeUntil": "ทำโอทีถึง {{time}}",
            "watchBackAt": "กลับ {{time}}",
            "watchNextShiftAt": "กะถัดไป {{time}}",
            "watchWidgetDescription": "เวลาที่เหลือและความคืบหน้าจนถึงเวลาเลิกงาน"
        ],
        "tr": [
            "watchCacheCorrupt": "Kayıtlı program okunamadı. iPhone’unuzda DoneAt’i açın.",
            "watchUpdateRequired": "Apple Watch’unuzda DoneAt’i güncelleyin.",
            "watchWaitingForIPhone": "iPhone bekleniyor",
            "watchSyncExpired": "Son güncellemenin süresi doldu.",
            "watchOpenIPhone": "iPhone’unuzda DoneAt’i açın.",
            "watchTimeLeftTitle": "Kalan süre",
            "watchTimeLeft": "{{duration}} kaldı",
            "watchOffAt": "Çıkış: {{time}}",
            "watchOvertimeUntil": "{{time}} saatine kadar mesai",
            "watchBackAt": "Dönüş: {{time}}",
            "watchNextShiftAt": "Sonraki vardiya: {{time}}",
            "watchWidgetDescription": "İş çıkışına kadar kalan süre ve ilerleme."
        ],
        "vi": [
            "watchCacheCorrupt": "Không thể đọc lịch đã lưu. Hãy mở DoneAt trên iPhone.",
            "watchUpdateRequired": "Hãy cập nhật DoneAt trên Apple Watch.",
            "watchWaitingForIPhone": "Đang chờ iPhone",
            "watchSyncExpired": "Bản cập nhật gần nhất đã hết hạn.",
            "watchOpenIPhone": "Mở DoneAt trên iPhone của bạn.",
            "watchTimeLeftTitle": "Thời gian còn lại",
            "watchTimeLeft": "Còn {{duration}}",
            "watchOffAt": "Tan ca lúc {{time}}",
            "watchOvertimeUntil": "Tăng ca đến {{time}}",
            "watchBackAt": "Quay lại lúc {{time}}",
            "watchNextShiftAt": "Ca tiếp theo lúc {{time}}",
            "watchWidgetDescription": "Thời gian còn lại và tiến độ cho đến khi tan ca."
        ]
    ]

    static func text(_ key: String, localeIdentifier: String? = nil) -> String {
        let candidates = localeIdentifier.map { [$0] } ?? Locale.preferredLanguages
        let locale = resolveLocale(candidates)
        if let value = values[locale]?[key] { return value }
        if let parent = parentLocale(locale), let value = values[parent]?[key] { return value }
        return values["en"]?[key] ?? key
    }

    /// Same region tables as `NativeLocalizer.resolve` and Android `AppLanguages.resolve`.
    /// Keep `scripts/regional-variants.mjs` in step with these sets.
    static func resolveLocale(_ candidates: [String]) -> String {
        for raw in candidates {
            let normalized = raw.replacingOccurrences(of: "_", with: "-")
            if let exact = supported.first(where: { $0.caseInsensitiveCompare(normalized) == .orderedSame }) { return exact }
            let lower = normalized.lowercased()
            if lower.hasPrefix("zh-hant-hk") || lower.hasPrefix("zh-hk") { return "zh-HK" }
            if lower.hasPrefix("zh-hant") || lower.hasPrefix("zh-tw") { return "zh-TW" }
            if lower.hasPrefix("zh") { return "zh-CN" }
            if lower == "en" || lower.hasPrefix("en-") { return isAmericanEnglish(lower) ? "en" : "en-GB" }
            if lower == "es" || lower.hasPrefix("es-") { return isLatinAmerican(lower) ? "es-MX" : "es" }
            if let language = supported.first(where: {
                lower.hasPrefix($0.lowercased() + "-") || $0.lowercased().hasPrefix(lower + "-")
            }) { return language }
        }
        return "en"
    }

    private static func parentLocale(_ locale: String) -> String? {
        switch locale {
        case "en-GB": return "en"
        case "es-MX": return "es"
        default: return nil
        }
    }

    private static func regionCode(_ tag: String) -> String? {
        let parts = tag.split(separator: "-").map(String.init)
        guard parts.count >= 2 else { return nil }
        var index = 1
        if parts[index].count == 4, parts[index].allSatisfy(\.isLetter) {
            index += 1
            guard index < parts.count else { return nil }
        }
        let region = parts[index]
        let letters = region.count == 2 && region.allSatisfy(\.isLetter)
        let digits = region.count == 3 && region.allSatisfy(\.isNumber)
        return (letters || digits) ? region.uppercased() : nil
    }

    private static func isAmericanEnglish(_ tag: String) -> Bool {
        guard let region = regionCode(tag) else { return true }
        return americanEnglishRegions.contains(region)
    }

    private static func isLatinAmerican(_ tag: String) -> Bool {
        guard let region = regionCode(tag) else { return false }
        return latinAmericanRegions.contains(region)
    }
}
