// Generated by scripts/generate-watch-shift-fixtures.mjs from lib/countdown.ts through
// scripts/build-ios-native-rules.mjs. Do not edit by hand.
import Foundation
@testable import App

nonisolated struct WatchShiftEvaluationFixture: Sendable {
    let name: String
    let nowMs: Int64
    let shift: WatchShiftProjectionV1
    let expected: WatchShiftEvaluation
}

nonisolated enum WatchShiftEvaluationFixtures {
    static let all: [WatchShiftEvaluationFixture] = [
        .init(
            name: "before-shift",
            nowMs: 1789345800000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789358400000), .init(startAtMs: 1789362000000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .before, totalMs: 25200000, elapsedMs: 0,
                remainingMs: 25200000, progress: 0, nextBoundaryAtMs: 1789347600000
            )
        ),
        .init(
            name: "lunch-working",
            nowMs: 1789351200000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789358400000), .init(startAtMs: 1789362000000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .working, totalMs: 25200000, elapsedMs: 3600000,
                remainingMs: 21600000, progress: 14.285714285714285, nextBoundaryAtMs: 1789358400000
            )
        ),
        .init(
            name: "lunch-start-boundary",
            nowMs: 1789358400000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789358400000), .init(startAtMs: 1789362000000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .resting, totalMs: 25200000, elapsedMs: 10800000,
                remainingMs: 14400000, progress: 42.857142857142854, nextBoundaryAtMs: 1789362000000
            )
        ),
        .init(
            name: "lunch-frozen",
            nowMs: 1789360200000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789358400000), .init(startAtMs: 1789362000000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .resting, totalMs: 25200000, elapsedMs: 10800000,
                remainingMs: 14400000, progress: 42.857142857142854, nextBoundaryAtMs: 1789362000000
            )
        ),
        .init(
            name: "lunch-end-boundary",
            nowMs: 1789362000000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789358400000), .init(startAtMs: 1789362000000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .working, totalMs: 25200000, elapsedMs: 10800000,
                remainingMs: 14400000, progress: 42.857142857142854, nextBoundaryAtMs: 1789376400000
            )
        ),
        .init(
            name: "lunch-resumed",
            nowMs: 1789365600000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789358400000), .init(startAtMs: 1789362000000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .working, totalMs: 25200000, elapsedMs: 14400000,
                remainingMs: 10800000, progress: 57.14285714285714, nextBoundaryAtMs: 1789376400000
            )
        ),
        .init(
            name: "overnight-before-midnight",
            nowMs: 1789426800000,
            shift: .init(
                segments: [.init(startAtMs: 1789423200000, endAtMs: 1789452000000)],
                plannedEndAtMs: 1789452000000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .working, totalMs: 28800000, elapsedMs: 3600000,
                remainingMs: 25200000, progress: 12.5, nextBoundaryAtMs: 1789452000000
            )
        ),
        .init(
            name: "overnight-after-midnight",
            nowMs: 1789437600000,
            shift: .init(
                segments: [.init(startAtMs: 1789423200000, endAtMs: 1789452000000)],
                plannedEndAtMs: 1789452000000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .working, totalMs: 28800000, elapsedMs: 14400000,
                remainingMs: 14400000, progress: 50, nextBoundaryAtMs: 1789452000000
            )
        ),
        .init(
            name: "overtime-before-boundary",
            nowMs: 1789376399999,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789383600000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: 1789383600000,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .working, totalMs: 36000000, elapsedMs: 28799999,
                remainingMs: 7200001, progress: 79.99999722222222, nextBoundaryAtMs: 1789376400000
            )
        ),
        .init(
            name: "overtime-boundary",
            nowMs: 1789376400000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789383600000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: 1789383600000,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .overtime, totalMs: 36000000, elapsedMs: 28800000,
                remainingMs: 7200000, progress: 80, nextBoundaryAtMs: 1789383600000
            )
        ),
        .init(
            name: "overtime",
            nowMs: 1789378200000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789383600000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: 1789383600000,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .overtime, totalMs: 36000000, elapsedMs: 30600000,
                remainingMs: 5400000, progress: 85, nextBoundaryAtMs: 1789383600000
            )
        ),
        .init(
            name: "dst-spring-forward",
            nowMs: 1772965800000,
            shift: .init(
                segments: [.init(startAtMs: 1772956800000, endAtMs: 1772982000000)],
                plannedEndAtMs: 1772982000000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .working, totalMs: 25200000, elapsedMs: 9000000,
                remainingMs: 16200000, progress: 35.714285714285715, nextBoundaryAtMs: 1772982000000
            )
        ),
        .init(
            name: "final-boundary",
            nowMs: 1789376400000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .finished, totalMs: 28800000, elapsedMs: 28800000,
                remainingMs: 0, progress: 100, nextBoundaryAtMs: nil
            )
        ),
        .init(
            name: "expired",
            nowMs: 1789380000000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: nil,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .finished, totalMs: 28800000, elapsedMs: 28800000,
                remainingMs: 0, progress: 100, nextBoundaryAtMs: nil
            )
        ),
        .init(
            name: "early-finish-working",
            nowMs: 1789372800000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789358400000), .init(startAtMs: 1789362000000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: 1789365600000,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .finished, totalMs: 25200000, elapsedMs: 14400000,
                remainingMs: 10800000, progress: 57.14285714285714, nextBoundaryAtMs: nil
            )
        ),
        .init(
            name: "early-finish-during-lunch",
            nowMs: 1789369200000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789358400000), .init(startAtMs: 1789362000000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: 1789360200000,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .finished, totalMs: 25200000, elapsedMs: 10800000,
                remainingMs: 14400000, progress: 42.857142857142854, nextBoundaryAtMs: nil
            )
        ),
        .init(
            name: "early-finish-frozen-after-clock-and-schedule-change",
            nowMs: 1789374600000,
            shift: .init(
                segments: [.init(startAtMs: 1789347600000, endAtMs: 1789358400000), .init(startAtMs: 1789362000000, endAtMs: 1789376400000)],
                plannedEndAtMs: 1789376400000,
                overtimeEndAtMs: nil,
                finishedAtMs: 1789354800000,
                isRunning: true,
                transitions: []
            ),
            expected: .init(
                phase: .finished, totalMs: 25200000, elapsedMs: 7200000,
                remainingMs: 18000000, progress: 28.57142857142857, nextBoundaryAtMs: nil
            )
        )
    ]
}
